{\rtf1\ansi\ansicpg1252\cocoartf1504\cocoasubrtf830
{\fonttbl\f0\fmodern\fcharset0 Courier;\f1\fswiss\fcharset0 Helvetica;}
{\colortbl;\red255\green255\blue255;\red57\green57\blue57;\red255\green255\blue255;}
{\*\expandedcolortbl;;\cssrgb\c28627\c28627\c28627;\cssrgb\c100000\c100000\c100000;}
\paperw11900\paperh16840\margl1440\margr1440\vieww10800\viewh8400\viewkind0
\deftab720
\pard\pardeftab720\sl360\sa600\partightenfactor0

\f0\fs32 \cf2 \cb3 \expnd0\expndtw0\kerning0
\outl0\strokewidth0 \strokec2 deployment:\cb1 \uc0\u8232 \cb3 production:\cb1 \uc0\u8232 \cb3 branch: master\cb1 \uc0\u8232 \cb3 commands:\cb1 \uc0\u8232 \cb3 - ./deploy_prod.sh
\f1 \

\f0 test:\cb1 \uc0\u8232 \cb3 override:\cb1 \uc0\u8232 \cb3 - echo 'no tests, just say us Okay!'
\f1 \
}